randomDataMin = 1
randomDataMax = 2137

#I will later on add other countries
listOfCountries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina	",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Democratic Republic of Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea", "Poland",
    "Great Britian",
    "India",
    "North Korea",
    "Pakistan",
    "South Africa",
    "United States of America",
    "Japan",
    "Yemen",
    "Serbia",
    "Germany",
]

#list of colors to randomise and use in random bar plots
listOfColors = [
    "#a04b07",
    "#5e2669",
    "#27dd95",
    "#195a79",
    "#fe7960",
    "#327362",
    "#135356",
    "#3f96a0",
    "#95f444",
    "#72fca2",
    "#2305ca",
    "#2f255c"
]
